# Generated by Django 3.0.8 on 2020-07-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='final_letter_grade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('P', 'Pass'), ('F', 'Fail'), ('W', 'Withdrawal'), ('I', 'Incomplete')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='midterm_letter_grade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('P', 'Pass'), ('F', 'Fail')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('WAIT', 'Waitlisted'), ('REG', 'Registered'), ('RPF', 'Registered Pass/Fail'), ('AUD', 'Auditing'), ('DROP', 'Dropped')], default='WAIT', max_length=4),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='assignment_grade',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
