# Generated by Django 3.0.8 on 2020-07-27 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_application', '0002_auto_20200721_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='section',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cms_application.Section'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_date', models.DateField()),
                ('announcement_text', models.CharField(max_length=1000)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_application.Section')),
            ],
        ),
    ]
