# Generated by Django 3.0.8 on 2020-07-28 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_application', '0005_announcement_announcement_title'),
        ('cms_application', '0002_auto_20200726_2008'),
    ]

    operations = [
    ]
