# Generated by Django 3.0.8 on 2020-07-31 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_application', '0006_merge_20200727_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='final_letter_grade',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='midterm_letter_grade',
        ),
    ]
