# Generated by Django 3.0.8 on 2020-07-31 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_application', '0007_auto_20200730_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentassignment',
            old_name='submission_file_name',
            new_name='submission_filename',
        ),
        migrations.AddField(
            model_name='assignment',
            name='instructions_filename',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='profile_picture_filename',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='profile_picture_filename',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='syllabus_filename',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_picture_filename',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
