# Generated by Django 3.0.8 on 2020-08-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_application', '0008_auto_20200730_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
