# Generated by Django 3.0.8 on 2020-08-06 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_application', '0009_auto_20200802_2308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalendarEvent',
        ),
    ]
