# Generated by Django 3.0.8 on 2020-08-09 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms_application', '0010_delete_calendarevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='instructions_filename',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='profile_picture_filename',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='professor',
            name='profile_picture_filename',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='syllabus_filename',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_picture_filename',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='submission_filename',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('staff_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
