# Generated by Django 3.0.8 on 2020-08-10 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_application', '0012_auto_20200809_1539'),
        ('cms_application', '0012_auto_20200809_1550'),
    ]

    operations = [
    ]
